default_language_version:
    python: python3
default_stages: [ commit ]

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-executables-have-shebangs
    - id: check-json
    - id: check-merge-conflict
    - id: check-toml
